# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# Build and push the docker
- task: Docker@2
  displayName: Login to the Dockerhub
  inputs:
    containerRegistry: 'docker-hub-conn'
    command: 'login'
- task: Docker@2
  displayName: Build and push the app to Dockerhub
  inputs:
    containerRegistry: 'docker-hub-conn'
    repository: 'raghavan16/shopping-ui'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

# Install Kubectl tool
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

# Update the kubeconfig file to point it to the aws eks cluster
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws-conn'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      aws eks update-kubeconfig --name terraform-eks-demo
      kubectl apply -f $(Build.SourcesDirectory)/kube-deploy.yaml
      kubectl apply -f $(Build.SourcesDirectory)/kube-service.yaml
