apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shopping-ui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shopping-ui
    spec:
      containers:
        - image: "raghavan16/shopping-ui"
          imagePullPolicy: Always
          name: shopping-ui
          ports:
            - containerPort: 8080

